// dyes.js — PanelCanvas v0.5
// Last updated: 2026-05-27
// Maintainer: Rosa Sottile, MSK Flow Cytometry Core
//
// =============================================================================
// SCHEMA — every entry is normalized at load time to contain these fields.
// Write entries compactly; defaults are filled in by _normalize() below.
// =============================================================================
//   name              canonical short form (e.g., 'RB780')
//   aliases           array of equivalent names from other vendors
//   category          UI grouping (e.g., 'BD Horizon Real', 'cFluor')
//   excite            primary laser line (355 | 405 | 488 | 561 | 638)
//   excite_alt        secondary laser(s); PE family = [488]
//   excite_max_nm     molecular ex peak when published (null otherwise)
//   emission          peak emission wavelength (nm)
//   brightness_index  1-5 unified scale (null if no data)
//   brightness_source provenance tag — see PRECEDENCE below
//   similarity_group  Cytek-derived cluster ID; scoring.js treats shared
//                     group as a hard conflict (spectrally identical)
//   is_tandem         true for FRET tandems (affects fix/perm sensitivity)
//   conventional_ok   false for spectral-only dyes (NovaFluor full line,
//                     several BD Reals, BV480, BUV-series, etc.)
//   unique_spectral_space  Thermo's claim for asterisked NovaFluors
//   substitutes       BD-style "use this instead" suggestions
//   status            'active' | 'discontinued'
//   replaced_by       (when status='discontinued')
//   source            which PDF/document this entry came from
//
// =============================================================================
// BRIGHTNESS PRECEDENCE (when multiple sources had data for the same dye):
// =============================================================================
//   1. thermo_si_chart_2025      — Thermo's multi-vendor SI chart (primary)
//   2. cytek_si_2021             — Cytek cFluor Selection Guidelines, Aurora
//   3. bd_real_normalized        — BD Horizon Real (1-4 × 1.25 → 1-5)
//   4. biolegend_published       — BioLegend Fluorophore MiniGuide native 1-5
//   5. biorad_ze5_visual         — Bio-Rad StarBright brochure (visual)
//   6. no_data                   — null; scoring.js applies low-confidence fallback
//
// =============================================================================
// SCORING.JS TOUCH POINTS (v0.5 changes that consume new schema fields):
// =============================================================================
//   - similarity_group: scoring.js short-circuits SI to 1.0 when both
//     dyes share the same group string.
//   - conventional_ok: scoring.js flags any dye with false on a conventional
//     panel as an incompatible-dye conflict.
//   - excite_alt: used by scoring.js to determine if a dye can excite on
//     instruments lacking the primary laser.
//   - brightness_index null: scoring.js treats as 3 with low_confidence:true.
//
// =============================================================================
// SOURCES MERGED:
// =============================================================================
//   - bd_horizon_real_table_2025      BD Horizon Real Dyes (17 dyes)
//   - biolegend_miniguide_2025        BioLegend Fluorophore Guide
//   - cytek_cfluor_guidelines_2021    Cytek cFluor Selection (37 cFluors +
//                                      similarity tables for ~150 dyes)
//   - biorad_starbright_brochure      Bio-Rad StarBright Dyes brochure (32)
//   - thermo_novafluor_catalog        Thermo NovaFluor catalog (33 dyes)
//   - thermo_si_chart_2025            Thermo multi-vendor SI chart
//
// =============================================================================
'use strict';

const _RAW_DYES = [

  // ============================================================
  // UV LASER (355 nm)
  // ============================================================

  // ── BD Brilliant UltraViolet (BUV) ────────────────────────────
  { name: 'BUV395', category: 'BD Horizon BUV', excite: 355, emission: 395,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    source: 'bd_brilliant_uv', aliases: ['BD Horizon BUV395'] },
  { name: 'BUV496', category: 'BD Horizon BUV', excite: 355, emission: 496,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    source: 'bd_brilliant_uv', aliases: ['BD Horizon BUV496'] },
  { name: 'BUV563', category: 'BD Horizon BUV', excite: 355, emission: 563,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    source: 'bd_brilliant_uv', aliases: ['BD Horizon BUV563'] },
  { name: 'BUV615', category: 'BD Horizon BUV', excite: 355, emission: 615,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    source: 'bd_brilliant_uv', aliases: ['BD Horizon BUV615'] },
  { name: 'BUV661', category: 'BD Horizon BUV', excite: 355, emission: 661,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    source: 'bd_brilliant_uv', aliases: ['BD Horizon BUV661'] },
  { name: 'BUV737', category: 'BD Horizon BUV', excite: 355, emission: 737,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    source: 'bd_brilliant_uv', aliases: ['BD Horizon BUV737'] },
  { name: 'BUV805', category: 'BD Horizon BUV', excite: 355, emission: 805,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    source: 'bd_brilliant_uv', aliases: ['BD Horizon BUV805'] },

  // ── BioLegend Spark UV ────────────────────────────────────────
  { name: 'Spark PLUS UV395', category: 'BioLegend Spark', excite: 355, emission: 395,
    brightness_index: 4, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark UV 387', category: 'BioLegend Spark', excite: 355, emission: 387,
    brightness_index: 2, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark PLUS UV490', category: 'BioLegend Spark', excite: 355, emission: 490,
    brightness_index: 2, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },

  // ── Bio-Rad StarBright UltraViolet (SBUV) ─────────────────────
  { name: 'SBUV400', category: 'Bio-Rad StarBright', excite: 355, emission: 400,
    brightness_index: 2, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright UltraViolet 400'] },
  { name: 'SBUV445', category: 'Bio-Rad StarBright', excite: 355, emission: 445,
    brightness_index: 1, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright UltraViolet 445'] },
  { name: 'SBUV510', category: 'Bio-Rad StarBright', excite: 355, emission: 510,
    brightness_index: 1, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright UltraViolet 510'] },
  { name: 'SBUV575', category: 'Bio-Rad StarBright', excite: 355, emission: 575,
    brightness_index: 1, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright UltraViolet 575'] },
  { name: 'SBUV605', category: 'Bio-Rad StarBright', excite: 355, emission: 605,
    brightness_index: 2, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright UltraViolet 605'] },
  { name: 'SBUV665', category: 'Bio-Rad StarBright', excite: 355, emission: 665,
    brightness_index: 2, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright UltraViolet 665'] },
  { name: 'SBUV740', category: 'Bio-Rad StarBright', excite: 355, emission: 740,
    brightness_index: 4, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright UltraViolet 740'] },
  { name: 'SBUV795', category: 'Bio-Rad StarBright', excite: 355, emission: 795,
    brightness_index: 4, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright UltraViolet 795'] },

  // ── Thermo NovaFluor UV (spectral only) ──────────────────────
  { name: 'NovaFluor UV 765', category: 'NovaFluor', excite: 355, excite_max_nm: 358, emission: 763,
    conventional_ok: false, unique_spectral_space: true,
    source: 'thermo_novafluor_catalog', aliases: ['NF UV 765'] },

  // ── UV viability + DNA dyes ──────────────────────────────────
  { name: 'DAPI', category: 'DNA dye', excite: 355, emission: 455,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Hoechst 33342', category: 'DNA dye', excite: 355, emission: 460,
    brightness_index: 4, brightness_source: 'manufacturer_published',
    source: 'thermo_published' },
  { name: 'Alexa Fluor 350', category: 'Alexa Fluor', excite: 355, emission: 442,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'UV_ld_blue_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'LIVE/DEAD Blue', category: 'LIVE/DEAD', excite: 355, emission: 446,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'UV_ld_blue_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'eFluor 455', category: 'eFluor', excite: 355, emission: 455,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    similarity_group: 'UV_zombie_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Ghost Dye UV 450', category: 'Tonbo Ghost Dye', excite: 355, emission: 450,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    similarity_group: 'UV_zombie_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Zombie UV', category: 'BioLegend Zombie', excite: 355, emission: 459,
    brightness_index: 2, brightness_source: 'biolegend_published',
    similarity_group: 'UV_zombie_cluster', source: 'biolegend_miniguide_2025' },
  { name: 'Zombie UV387', category: 'BioLegend Zombie', excite: 355, emission: 387,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },

  // ── Cytek cFluor UV ──────────────────────────────────────────
  { name: 'cFluor UV395', category: 'cFluor', excite: 355, emission: 395,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor UV440', category: 'cFluor', excite: 355, emission: 440,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor UV515', category: 'cFluor', excite: 355, emission: 515,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor UV570', category: 'cFluor', excite: 355, emission: 570,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor UV610', category: 'cFluor', excite: 355, emission: 610,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor UV670', category: 'cFluor', excite: 355, emission: 670,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor UV745', category: 'cFluor', excite: 355, emission: 745,
    brightness_index: 4, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor UV790', category: 'cFluor', excite: 355, emission: 790,
    brightness_index: 4, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },

  // ============================================================
  // VIOLET LASER (405 nm)
  // ============================================================

  // ── BD/BioLegend Brilliant Violet (BV) — Sirigen-licensed ─────
  { name: 'BV421', category: 'Brilliant Violet', excite: 405, emission: 421,
    brightness_index: 5, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021', aliases: ['Brilliant Violet 421'] },
  { name: 'BV480', category: 'Brilliant Violet', excite: 405, emission: 480,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'cytek_cfluor_guidelines_2021',
    aliases: ['Brilliant Violet 480'] },
  { name: 'BV510', category: 'Brilliant Violet', excite: 405, emission: 510,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V510_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['Brilliant Violet 510'] },
  { name: 'BV570', category: 'Brilliant Violet', excite: 405, emission: 570,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021', aliases: ['Brilliant Violet 570'] },
  { name: 'BV605', category: 'Brilliant Violet', excite: 405, emission: 603,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V605_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021', aliases: ['Brilliant Violet 605'] },
  { name: 'BV650', category: 'Brilliant Violet', excite: 405, emission: 645,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V650_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021', aliases: ['Brilliant Violet 650'] },
  { name: 'BV711', category: 'Brilliant Violet', excite: 405, emission: 711,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V711_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021', aliases: ['Brilliant Violet 711'] },
  { name: 'BV750', category: 'Brilliant Violet', excite: 405, emission: 750,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    is_tandem: true, source: 'cytek_cfluor_guidelines_2021',
    aliases: ['Brilliant Violet 750'] },
  { name: 'BV785', category: 'Brilliant Violet', excite: 405, emission: 785,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V785_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021', aliases: ['Brilliant Violet 785', 'BV786'] },

  // ── Thermo Super Bright (SB) — DISTINCT from Bio-Rad StarBright ──
  { name: 'Super Bright 436', category: 'Thermo Super Bright', excite: 405, emission: 436,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V420_cluster', source: 'thermo_published' },
  { name: 'Super Bright 600', category: 'Thermo Super Bright', excite: 405, emission: 600,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V605_cluster', source: 'thermo_published' },
  { name: 'Super Bright 645', category: 'Thermo Super Bright', excite: 405, emission: 645,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V650_cluster', source: 'thermo_published' },
  { name: 'Super Bright 702', category: 'Thermo Super Bright', excite: 405, emission: 702,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    source: 'thermo_published' },
  { name: 'Super Bright 780', category: 'Thermo Super Bright', excite: 405, emission: 780,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    source: 'thermo_published' },

  // ── BioLegend Spark Violet / PLUS V ──────────────────────────
  { name: 'Spark Violet 423', category: 'BioLegend Spark', excite: 405, emission: 423,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark PLUS V475', category: 'BioLegend Spark', excite: 405, emission: 475,
    brightness_index: 4, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark Violet 500', category: 'BioLegend Spark', excite: 405, emission: 500,
    brightness_index: 1, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark Violet 538', category: 'BioLegend Spark', excite: 405, emission: 538,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    source: 'biolegend_miniguide_2025', aliases: ['Spark V538'],
    substitutes: ['RV544', 'cFluor V547'] },

  // ── Cytek cFluor Violet ──────────────────────────────────────
  { name: 'cFluor V420', category: 'cFluor', excite: 405, emission: 420,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    similarity_group: 'V420_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V435', category: 'cFluor', excite: 405, emission: 435,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V450', category: 'cFluor', excite: 405, emission: 450,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'V450_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V475', category: 'cFluor', excite: 405, emission: 475,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V505', category: 'cFluor', excite: 405, emission: 505,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V515', category: 'cFluor', excite: 405, emission: 515,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V547', category: 'cFluor', excite: 405, emission: 547,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    similarity_group: 'V547_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V570', category: 'cFluor', excite: 405, emission: 570,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V605', category: 'cFluor', excite: 405, emission: 605,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V610', category: 'cFluor', excite: 405, emission: 610,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V670', category: 'cFluor', excite: 405, emission: 670,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V715', category: 'cFluor', excite: 405, emission: 715,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V755', category: 'cFluor', excite: 405, emission: 755,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor V780', category: 'cFluor', excite: 405, emission: 780,
    brightness_index: 4, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },

  // ── Bio-Rad StarBright Violet (SBV) ──────────────────────────
  { name: 'SBV440', category: 'Bio-Rad StarBright', excite: 405, emission: 440,
    brightness_index: 3, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Violet 440'] },
  { name: 'SBV475', category: 'Bio-Rad StarBright', excite: 405, emission: 475,
    brightness_index: 2, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Violet 475'] },
  { name: 'SBV515', category: 'Bio-Rad StarBright', excite: 405, emission: 515,
    brightness_index: 3, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Violet 515'] },
  { name: 'SBV570', category: 'Bio-Rad StarBright', excite: 405, emission: 570,
    brightness_index: 1, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Violet 570'] },
  { name: 'SBV610', category: 'Bio-Rad StarBright', excite: 405, emission: 610,
    brightness_index: 2, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Violet 610'] },
  { name: 'SBV670', category: 'Bio-Rad StarBright', excite: 405, emission: 670,
    brightness_index: 4, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Violet 670'] },
  { name: 'SBV710', category: 'Bio-Rad StarBright', excite: 405, emission: 710,
    brightness_index: 3, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Violet 710'] },
  { name: 'SBV760', category: 'Bio-Rad StarBright', excite: 405, emission: 760,
    brightness_source: 'biorad_ze5_visual', source: 'biorad_starbright_brochure',
    aliases: ['StarBright Violet 760'] },
  { name: 'SBV790', category: 'Bio-Rad StarBright', excite: 405, emission: 790,
    brightness_index: 4, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Violet 790'] },

  // ── Thermo NovaFluor Violet (spectral only) ──────────────────
  { name: 'NovaFluor Violet 690', category: 'NovaFluor', excite: 405, excite_max_nm: 408, emission: 691,
    conventional_ok: false, unique_spectral_space: true,
    source: 'thermo_novafluor_catalog', aliases: ['NF V 690'] },
  { name: 'NovaFluor Violet 745', category: 'NovaFluor', excite: 405, excite_max_nm: 391, emission: 743,
    conventional_ok: false, unique_spectral_space: true,
    source: 'thermo_novafluor_catalog', aliases: ['NF V 745'] },
  { name: 'NovaFluor Violet 800', category: 'NovaFluor', excite: 405, excite_max_nm: 408, emission: 800,
    conventional_ok: false, unique_spectral_space: true,
    source: 'thermo_novafluor_catalog', aliases: ['NF V 800', 'NovaFluor V800'] },

  // ── BD Horizon Real Violet ───────────────────────────────────
  { name: 'RV544', category: 'BD Horizon Real', excite: 405, emission: 544,
    brightness_index: 3, brightness_source: 'bd_real_normalized',
    conventional_ok: false, source: 'bd_horizon_real_table_2025',
    aliases: ['BD Horizon RealViolet 544'],
    substitutes: ['Spark V538', 'Pacific Orange', 'Amethyst Orange', 'cFluor V547', 'Krome Orange'] },
  { name: 'RV828', category: 'BD Horizon Real', excite: 405, emission: 828,
    brightness_index: 3, brightness_source: 'bd_real_normalized',
    conventional_ok: false, source: 'bd_horizon_real_table_2025',
    aliases: ['BD Horizon RealViolet 828'],
    substitutes: ['Qdot 800', 'NovaFluor Violet 800'] },

  // ── Violet viability / V450 cluster ──────────────────────────
  { name: 'Pacific Blue', category: 'Pacific Blue', excite: 405, emission: 455,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V450_cluster', source: 'biolegend_miniguide_2025',
    aliases: ['PB'] },
  { name: 'eFluor 450', category: 'eFluor', excite: 405, emission: 450,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'V450_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'V450', category: 'BD V450', excite: 405, emission: 450,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'V450_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['BD Horizon V450'] },
  { name: 'VioBlue', category: 'Miltenyi Vio', excite: 405, emission: 450,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'V450_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'violetFluor 450', category: 'Tonbo violetFluor', excite: 405, emission: 450,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'V450_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Ghost Dye Violet 450', category: 'Tonbo Ghost Dye', excite: 405, emission: 450,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'V450_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'LIVE/DEAD Violet', category: 'LIVE/DEAD', excite: 405, emission: 450,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'V450_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Fixable Viability Stain 450', category: 'BD FVS', excite: 405, emission: 450,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'V450_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['FVS 450'] },
  { name: 'Zombie Violet', category: 'BioLegend Zombie', excite: 405, emission: 423,
    brightness_index: 4, brightness_source: 'biolegend_published',
    similarity_group: 'V420_cluster', source: 'biolegend_miniguide_2025' },
  { name: 'CellTrace Violet', category: 'Thermo CellTrace', excite: 405, emission: 450,
    brightness_index: 4, brightness_source: 'manufacturer_published',
    similarity_group: 'V450_cluster', source: 'cytek_cfluor_guidelines_2021' },

  // ── V510 cluster (BV510-equivalents) ─────────────────────────
  { name: 'Pacific Orange', category: 'Pacific Orange', excite: 405, emission: 551,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V547_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Krome Orange', category: 'Beckman Krome', excite: 405, emission: 528,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V510_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Amethyst Orange', category: 'Amethyst Orange', excite: 405, emission: 549,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'V500', category: 'BD V500', excite: 405, emission: 500,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V510_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'eFluor 506', category: 'eFluor', excite: 405, emission: 506,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    similarity_group: 'V510_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'VioGreen', category: 'Miltenyi Vio', excite: 405, emission: 520,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    similarity_group: 'V510_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'LIVE/DEAD Aqua', category: 'LIVE/DEAD', excite: 405, emission: 516,
    brightness_index: 2, brightness_source: 'manufacturer_published',
    similarity_group: 'V510_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Zombie Aqua', category: 'BioLegend Zombie', excite: 405, emission: 516,
    brightness_index: 3, brightness_source: 'biolegend_published',
    similarity_group: 'V510_cluster', source: 'biolegend_miniguide_2025' },
  { name: 'OC515', category: 'Cytognos OC', excite: 405, emission: 515,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    similarity_group: 'V510_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Ghost Dye Violet 510', category: 'Tonbo Ghost Dye', excite: 405, emission: 510,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    similarity_group: 'V510_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Fixable Viability Stain 510', category: 'BD FVS', excite: 405, emission: 510,
    brightness_index: 1, brightness_source: 'manufacturer_published',
    similarity_group: 'V510_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['FVS 510'] },
  { name: 'violetFluor 500', category: 'Tonbo violetFluor', excite: 405, emission: 500,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },

  // ── V547 cluster (Pacific Orange-equivalents) ────────────────
  { name: 'LIVE/DEAD Yellow', category: 'LIVE/DEAD', excite: 405, emission: 575,
    brightness_index: 2, brightness_source: 'manufacturer_published',
    similarity_group: 'V547_cluster', source: 'cytek_cfluor_guidelines_2021' },

  // ── V605 cluster ─────────────────────────────────────────────
  { name: 'Qdot 605', category: 'Qdot', excite: 405, emission: 605,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V605_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Zombie Yellow', category: 'BioLegend Zombie', excite: 405, emission: 572,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },

  // ── V650 / V711 / V785 clusters ──────────────────────────────
  { name: 'Qdot 655', category: 'Qdot', excite: 405, emission: 655,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V650_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Qdot 705', category: 'Qdot', excite: 405, emission: 705,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V711_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Qdot 800', category: 'Qdot', excite: 405, emission: 800,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'V785_cluster', source: 'cytek_cfluor_guidelines_2021' },

  // ============================================================
  // BLUE LASER (488 nm)
  // ============================================================

  // ── FITC / AF488 / B515 cluster ──────────────────────────────
  { name: 'FITC', category: 'FITC', excite: 488, emission: 525,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'B532_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Alexa Fluor 488', category: 'Alexa Fluor', excite: 488, emission: 519,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'B532_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['AF488'] },
  { name: 'BB515', category: 'BD Brilliant Blue', excite: 488, emission: 515,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'B515_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['Brilliant Blue 515'] },
  { name: 'KIRAVIA Blue 520', category: 'Sony KIRAVIA', excite: 488, emission: 520,
    brightness_index: 4, brightness_source: 'biolegend_published',
    similarity_group: 'B532_cluster', source: 'biolegend_miniguide_2025' },
  { name: 'CFSE', category: 'Thermo CellTrace', excite: 488, emission: 517,
    brightness_index: 4, brightness_source: 'manufacturer_published',
    similarity_group: 'B532_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['CellTrace CFSE'] },
  { name: 'Vio 515', category: 'Miltenyi Vio', excite: 488, emission: 515,
    brightness_index: 4, brightness_source: 'cytek_si_2021',
    similarity_group: 'B515_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Spark PLUS B488', category: 'BioLegend Spark', excite: 488, emission: 519,
    brightness_index: 5, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark Blue 515', category: 'BioLegend Spark', excite: 488, emission: 515,
    brightness_index: 2, brightness_source: 'biolegend_published',
    similarity_group: 'B515_cluster', source: 'biolegend_miniguide_2025' },
  { name: 'Ghost Dye Blue 516', category: 'Tonbo Ghost Dye', excite: 488, emission: 516,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'B532_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Zombie Green', category: 'BioLegend Zombie', excite: 488, emission: 515,
    brightness_index: 3, brightness_source: 'biolegend_published',
    similarity_group: 'B532_cluster', source: 'biolegend_miniguide_2025' },

  // ── Cytek cFluor Blue ────────────────────────────────────────
  { name: 'cFluor B515', category: 'cFluor', excite: 488, emission: 515,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'B515_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor B520', category: 'cFluor', excite: 488, emission: 520,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor B532', category: 'cFluor', excite: 488, emission: 532,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'B532_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor B548', category: 'cFluor', excite: 488, emission: 548,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'B548_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor B675', category: 'cFluor', excite: 488, emission: 675,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor B690', category: 'cFluor', excite: 488, emission: 690,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    similarity_group: 'B690_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },

  // ── Bio-Rad StarBright Blue (SBB) ────────────────────────────
  { name: 'SBB580', category: 'Bio-Rad StarBright', excite: 488, emission: 580,
    brightness_index: 3, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Blue 580'] },
  { name: 'SBB615', category: 'Bio-Rad StarBright', excite: 488, emission: 615,
    brightness_index: 4, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Blue 615'] },
  { name: 'SBB675', category: 'Bio-Rad StarBright', excite: 488, emission: 675,
    brightness_index: 4, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Blue 675'] },
  { name: 'SBB700', category: 'Bio-Rad StarBright', excite: 488, emission: 700,
    brightness_index: 2, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Blue 700'] },
  { name: 'SBB765', category: 'Bio-Rad StarBright', excite: 488, emission: 765,
    brightness_index: 5, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Blue 765'] },
  { name: 'SBB810', category: 'Bio-Rad StarBright', excite: 488, emission: 810,
    brightness_index: 4, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Blue 810'] },

  // ── BD Horizon Real Blue ─────────────────────────────────────
  { name: 'RB545', category: 'BD Horizon Real', excite: 488, emission: 545,
    brightness_index: 3, brightness_source: 'bd_real_normalized',
    conventional_ok: false, source: 'bd_horizon_real_table_2025',
    aliases: ['BD Horizon RealBlue 545'] },
  { name: 'RB575', category: 'BD Horizon Real', excite: 488, emission: 575,
    brightness_index: 3, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealBlue 575'],
    substitutes: ['PE', 'SBB580'] },
  { name: 'RB613', category: 'BD Horizon Real', excite: 488, emission: 613,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealBlue 613'],
    substitutes: ['PE-CF594', 'PE-Dazzle 594', 'SBB615'] },
  { name: 'RB670', category: 'BD Horizon Real', excite: 488, emission: 670,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealBlue 670'],
    substitutes: ['PE-Cy5', 'SBB675'] },
  { name: 'RB705', category: 'BD Horizon Real', excite: 488, emission: 705,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealBlue 705'],
    substitutes: ['PerCP-Cy5.5', 'BB700', 'SBB700'] },
  { name: 'RB744', category: 'BD Horizon Real', excite: 488, emission: 744,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealBlue 744'] },
  { name: 'RB780', category: 'BD Horizon Real', excite: 488, emission: 780,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealBlue 780'],
    substitutes: ['PE-Cy7', 'BB790'] },
  { name: 'RB824', category: 'BD Horizon Real', excite: 488, emission: 824,
    brightness_index: 4, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealBlue 824'],
    substitutes: ['PerCP/Fire 806', 'SBB810'] },

  // ── PerCP family ─────────────────────────────────────────────
  { name: 'PerCP', category: 'PerCP', excite: 488, emission: 675,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    source: 'biolegend_miniguide_2025' },
  { name: 'PerCP-Cy5.5', category: 'PerCP', excite: 488, emission: 690,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'B690_cluster', is_tandem: true,
    source: 'biolegend_miniguide_2025', aliases: ['PerCP/Cyanine5.5'] },
  { name: 'PerCP-eFluor 710', category: 'PerCP', excite: 488, emission: 710,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'B710_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'PerCP-Vio 700', category: 'PerCP', excite: 488, emission: 700,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'B710_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'PerCP/Fire 780', category: 'PerCP-Fire', excite: 488, emission: 774,
    brightness_index: 3, brightness_source: 'biolegend_published',
    is_tandem: true, source: 'biolegend_miniguide_2025' },
  { name: 'PerCP/Fire 806', category: 'PerCP-Fire', excite: 488, emission: 806,
    brightness_index: 3, brightness_source: 'biolegend_published',
    is_tandem: true, source: 'biolegend_miniguide_2025' },

  // ── BD Brilliant Blue (BB) ───────────────────────────────────
  { name: 'BB630', category: 'BD Brilliant Blue', excite: 488, emission: 630,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'BB660', category: 'BD Brilliant Blue', excite: 488, emission: 660,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'BB700', category: 'BD Brilliant Blue', excite: 488, emission: 700,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'B690_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'BB755', category: 'BD Brilliant Blue', excite: 488, emission: 755,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'BB790', category: 'BD Brilliant Blue', excite: 488, emission: 790,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021' },

  // ── BioLegend Spark Blue ─────────────────────────────────────
  { name: 'Spark PLUS B550', category: 'BioLegend Spark', excite: 488, emission: 540,
    brightness_index: 4, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark Blue 550', category: 'BioLegend Spark', excite: 488, emission: 540,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'B548_cluster', source: 'biolegend_miniguide_2025' },
  { name: 'Spark PLUS B574', category: 'BioLegend Spark', excite: 488, emission: 574,
    brightness_index: 4, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark Blue 574', category: 'BioLegend Spark', excite: 488, emission: 574,
    brightness_index: 1, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },

  // ── Thermo NovaFluor Blue (spectral only) ────────────────────
  { name: 'NovaFluor Blue 510', category: 'NovaFluor', excite: 488, excite_max_nm: 496, emission: 511,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B510'] },
  { name: 'NovaFluor Blue 530', category: 'NovaFluor', excite: 488, excite_max_nm: 509, emission: 530,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B530'] },
  { name: 'NovaFluor Blue 555', category: 'NovaFluor', excite: 488, excite_max_nm: 494, emission: 555,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B555'] },
  { name: 'NovaFluor Blue 585', category: 'NovaFluor', excite: 488, excite_max_nm: 494, emission: 585,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B585'] },
  { name: 'NovaFluor Blue 610-30S', category: 'NovaFluor', excite: 488, excite_max_nm: 509, emission: 614,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B610-30S'] },
  { name: 'NovaFluor Blue 610-70S', category: 'NovaFluor', excite: 488, excite_max_nm: 509, emission: 614,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B610-70S'] },
  { name: 'NovaFluor Blue 660-40S', category: 'NovaFluor', excite: 488, excite_max_nm: 509, emission: 665,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B660-40S'] },
  { name: 'NovaFluor Blue 660-120S', category: 'NovaFluor', excite: 488, excite_max_nm: 509, emission: 665,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B660-120S'] },
  { name: 'NovaFluor Blue 690', category: 'NovaFluor', excite: 488, excite_max_nm: 494, emission: 690,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B690'] },
  { name: 'NovaFluor Blue 725', category: 'NovaFluor', excite: 488, excite_max_nm: 492, emission: 725,
    conventional_ok: false, unique_spectral_space: true,
    source: 'thermo_novafluor_catalog', aliases: ['NF B725'] },
  { name: 'NovaFluor Blue 745', category: 'NovaFluor', excite: 488, excite_max_nm: 492, emission: 750,
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B745'] },
  { name: 'NovaFluor Blue 760', category: 'NovaFluor', excite: 488, excite_max_nm: 490, emission: 764,
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF B760'] },
  { name: 'NovaFluor Blue 800', category: 'NovaFluor', excite: 488, excite_max_nm: 493, emission: 806,
    conventional_ok: false, unique_spectral_space: true,
    source: 'thermo_novafluor_catalog', aliases: ['NF B800'] },

  // ── B548 / NorthernLights / VioBright ────────────────────────
  { name: 'Alexa Fluor 532', category: 'Alexa Fluor', excite: 488, emission: 553,
    brightness_index: 1, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021', aliases: ['AF532'] },
  { name: 'NorthernLights 493', category: 'NorthernLights', excite: 488, emission: 514,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021', aliases: ['NL493'] },
  { name: 'VioBright FITC', category: 'Miltenyi VioBright', excite: 488, emission: 519,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'B548_cluster', source: 'cytek_cfluor_guidelines_2021' },

  // ── Blue viability ───────────────────────────────────────────
  { name: 'eFluor 520', category: 'eFluor', excite: 488, emission: 520,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'B548_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Fixable Viability Stain 520', category: 'BD FVS', excite: 488, emission: 520,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'B548_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['FVS 520', 'Fixable Viability Dye 520'] },
  { name: 'LIVE/DEAD Green', category: 'LIVE/DEAD', excite: 488, emission: 519,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'B548_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Helix NP Blue', category: 'BioLegend Helix NP', excite: 488, emission: 470,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Helix NP Green', category: 'BioLegend Helix NP', excite: 488, emission: 519,
    brightness_index: 3, brightness_source: 'biolegend_published',
    similarity_group: 'B548_cluster', source: 'biolegend_miniguide_2025' },
  { name: 'Zombie B550', category: 'BioLegend Zombie', excite: 488, emission: 540,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },

  // ============================================================
  // YELLOW-GREEN LASER (561 nm)
  // PE family dual-excited by 488 and 561 (excite_alt: [488])
  // ============================================================

  // ── PE and PE-tandems (excite_alt = [488]) ──────────────────
  { name: 'PE', category: 'PE', excite: 561, excite_alt: [488], emission: 575,
    brightness_index: 5, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG1_cluster', source: 'biolegend_miniguide_2025',
    aliases: ['R-PE', 'Phycoerythrin'] },
  { name: 'PE-Dazzle 594', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 610,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG3_cluster', is_tandem: true,
    source: 'biolegend_miniguide_2025', aliases: ['PE/Dazzle 594'] },
  { name: 'PE-CF594', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 620,
    brightness_index: 5, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG3_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'PE-Texas Red', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 615,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG3_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'ECD', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 610,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG3_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'PE-Cy5', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 670,
    brightness_index: 5, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG5_cluster', is_tandem: true,
    source: 'biolegend_miniguide_2025', aliases: ['PE/Cyanine5'] },
  { name: 'PE-Cy5.5', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 695,
    brightness_index: 5, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG7_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'PE-Cy7', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 774,
    brightness_index: 5, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG9_cluster', is_tandem: true,
    source: 'biolegend_miniguide_2025', aliases: ['PE/Cyanine7'] },
  { name: 'PE-Vio 615', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 615,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG3_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'PE-Vio 770', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 770,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG9_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'PE-eFluor 610', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 610,
    brightness_index: 5, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG3_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'PE-Alexa Fluor 610', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 626,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG4_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'PE-Alexa Fluor 700', category: 'PE-tandem', excite: 561, excite_alt: [488], emission: 723,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'YG7_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },

  // ── PE-Fire family (BioLegend tandems) ───────────────────────
  { name: 'PE-Fire 640', category: 'PE-Fire', excite: 561, excite_alt: [488], emission: 639,
    brightness_index: 5, brightness_source: 'thermo_si_chart_2025',
    is_tandem: true, source: 'biolegend_miniguide_2025', aliases: ['PE/Fire 640'] },
  { name: 'PE-Fire 700', category: 'PE-Fire', excite: 561, excite_alt: [488], emission: 695,
    brightness_index: 5, brightness_source: 'biolegend_published',
    similarity_group: 'YG7_cluster', is_tandem: true,
    source: 'biolegend_miniguide_2025', aliases: ['PE/Fire 700'] },
  { name: 'PE-Fire 744', category: 'PE-Fire', excite: 561, excite_alt: [488], emission: 744,
    brightness_index: 5, brightness_source: 'biolegend_published',
    is_tandem: true, source: 'biolegend_miniguide_2025', aliases: ['PE/Fire 744'] },
  { name: 'PE-Fire 810', category: 'PE-Fire', excite: 561, excite_alt: [488], emission: 806,
    brightness_index: 4, brightness_source: 'biolegend_published',
    is_tandem: true, source: 'biolegend_miniguide_2025', aliases: ['PE/Fire 810'] },

  // ── BD Horizon Real Yellow-Green ─────────────────────────────
  { name: 'RY586', category: 'BD Horizon Real', excite: 561, emission: 586,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealYellow 586'],
    substitutes: ['PE'] },
  { name: 'RY610', category: 'BD Horizon Real', excite: 561, emission: 610,
    brightness_index: 4, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealYellow 610'],
    substitutes: ['PE-CF594', 'PE-Dazzle 594'] },
  { name: 'RY655', category: 'BD Horizon Real', excite: 561, emission: 655,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealYellow 655'],
    substitutes: ['PE-Cy5', 'SBY665'] },
  { name: 'RY703', category: 'BD Horizon Real', excite: 561, emission: 703,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealYellow 703'],
    substitutes: ['PE-Cy5.5', 'SBY720'] },
  { name: 'RY743', category: 'BD Horizon Real', excite: 561, emission: 743,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealYellow 743'],
    substitutes: ['PE-Fire 744'] },
  { name: 'RY775', category: 'BD Horizon Real', excite: 561, emission: 775,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    source: 'bd_horizon_real_table_2025', aliases: ['BD Horizon RealYellow 775'],
    substitutes: ['PE-Cy7', 'SBY800'] },

  // ── Cytek cFluor YG / BYG ────────────────────────────────────
  { name: 'cFluor YG584', category: 'cFluor', excite: 561, emission: 584,
    brightness_index: 4, brightness_source: 'cytek_si_2021',
    similarity_group: 'YG1_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor YG600', category: 'cFluor', excite: 561, emission: 600,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor YG610', category: 'cFluor', excite: 561, emission: 610,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor BYG575', category: 'cFluor', excite: 561, excite_alt: [488], emission: 575,
    brightness_index: 5, brightness_source: 'cytek_si_2021',
    similarity_group: 'YG1_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor BYG610', category: 'cFluor', excite: 561, excite_alt: [488], emission: 610,
    brightness_index: 5, brightness_source: 'cytek_si_2021',
    similarity_group: 'YG3_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor BYG645', category: 'cFluor', excite: 561, excite_alt: [488], emission: 645,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor BYG667', category: 'cFluor', excite: 561, excite_alt: [488], emission: 667,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'YG5_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor BYG680', category: 'cFluor', excite: 561, excite_alt: [488], emission: 680,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor BYG710', category: 'cFluor', excite: 561, excite_alt: [488], emission: 710,
    brightness_index: 4, brightness_source: 'cytek_si_2021',
    similarity_group: 'YG7_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor BYG750', category: 'cFluor', excite: 561, excite_alt: [488], emission: 750,
    brightness_index: 4, brightness_source: 'cytek_si_2021',
    is_tandem: true, source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor BYG781', category: 'cFluor', excite: 561, excite_alt: [488], emission: 781,
    brightness_index: 4, brightness_source: 'cytek_si_2021',
    similarity_group: 'YG9_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },

  // ── Bio-Rad StarBright Yellow (SBY) ──────────────────────────
  { name: 'SBY575', category: 'Bio-Rad StarBright', excite: 561, emission: 575,
    brightness_index: 4, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Yellow 575'] },
  { name: 'SBY605', category: 'Bio-Rad StarBright', excite: 561, emission: 605,
    brightness_index: 4, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Yellow 605'] },
  { name: 'SBY665', category: 'Bio-Rad StarBright', excite: 561, emission: 665,
    brightness_index: 5, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Yellow 665'] },
  { name: 'SBY720', category: 'Bio-Rad StarBright', excite: 561, emission: 720,
    brightness_index: 5, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Yellow 720'] },
  { name: 'SBY800', category: 'Bio-Rad StarBright', excite: 561, emission: 800,
    brightness_index: 5, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Yellow 800'] },

  // ── BioLegend Spark YG ───────────────────────────────────────
  { name: 'Spark PLUS YG581', category: 'BioLegend Spark', excite: 561, emission: 581,
    brightness_index: 4, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark YG 581', category: 'BioLegend Spark', excite: 561, emission: 581,
    brightness_index: 2, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark YG 593', category: 'BioLegend Spark', excite: 561, emission: 593,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark YG 570', category: 'BioLegend Spark', excite: 561, emission: 570,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'YG1_cluster', status: 'discontinued', replaced_by: 'Spark YG 581',
    source: 'cytek_cfluor_guidelines_2021' },

  // ── Thermo NovaFluor Yellow (spectral only) ──────────────────
  { name: 'NovaFluor Yellow 570', category: 'NovaFluor', excite: 561, excite_max_nm: 552, emission: 568,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF Y570'] },
  { name: 'NovaFluor Yellow 590', category: 'NovaFluor', excite: 561, excite_max_nm: 552, emission: 590,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF Y590'] },
  { name: 'NovaFluor Yellow 610', category: 'NovaFluor', excite: 561, excite_max_nm: 552, emission: 612,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF Y610'] },
  { name: 'NovaFluor Yellow 660', category: 'NovaFluor', excite: 561, excite_max_nm: 552, emission: 663,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF Y660'] },
  { name: 'NovaFluor Yellow 690', category: 'NovaFluor', excite: 561, excite_max_nm: 552, emission: 690,
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF Y690'] },
  { name: 'NovaFluor Yellow 700', category: 'NovaFluor', excite: 561, excite_max_nm: 552, emission: 700,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF Y700'] },
  { name: 'NovaFluor Yellow 730', category: 'NovaFluor', excite: 561, excite_max_nm: 552, emission: 731,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF Y730'] },
  { name: 'NovaFluor Yellow 755', category: 'NovaFluor', excite: 561, excite_max_nm: 552, emission: 755,
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF Y755'] },
  { name: 'NovaFluor Yellow 810', category: 'NovaFluor', excite: 561, excite_max_nm: 551, emission: 813,
    conventional_ok: false, unique_spectral_space: true,
    source: 'thermo_novafluor_catalog', aliases: ['NF Y810'] },

  // ── YG viability and reference ───────────────────────────────
  { name: '7-AAD', category: 'DNA dye', excite: 561, excite_alt: [488], emission: 647,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'YG4_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'PI', category: 'DNA dye', excite: 561, emission: 617,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'YG4_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['Propidium Iodide'] },
  { name: 'Fixable Viability Stain 575V', category: 'BD FVS', excite: 405, emission: 575,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    source: 'cytek_cfluor_guidelines_2021', aliases: ['FVS 575V'] },
  { name: 'Fixable Viability Stain 620', category: 'BD FVS', excite: 561, emission: 620,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'YG4_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['FVS 620'] },
  { name: 'Zombie YG581', category: 'BioLegend Zombie', excite: 561, emission: 581,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Zombie Red', category: 'BioLegend Zombie', excite: 561, emission: 624,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'NorthernLights 557', category: 'NorthernLights', excite: 561, emission: 557,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    similarity_group: 'YG1_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['NL557'] },

  // ============================================================
  // RED LASER (638 nm)
  // ============================================================

  // ── APC and Red core ─────────────────────────────────────────
  { name: 'APC', category: 'APC', excite: 638, emission: 660,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R1_cluster', source: 'biolegend_miniguide_2025',
    aliases: ['Allophycocyanin'] },
  { name: 'Alexa Fluor 647', category: 'Alexa Fluor', excite: 638, emission: 668,
    brightness_index: 5, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R2_cluster', source: 'biolegend_miniguide_2025',
    aliases: ['AF647'] },
  { name: 'Alexa Fluor 660', category: 'Alexa Fluor', excite: 638, emission: 690,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021', aliases: ['AF660'] },
  { name: 'Alexa Fluor 680', category: 'Alexa Fluor', excite: 638, emission: 702,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    similarity_group: 'R4_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['AF680'] },
  { name: 'Alexa Fluor 700', category: 'Alexa Fluor', excite: 638, emission: 719,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R4_cluster', source: 'biolegend_miniguide_2025',
    aliases: ['AF700'] },
  { name: 'Alexa Fluor 750', category: 'Alexa Fluor', excite: 638, emission: 776,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R7_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['AF750'] },
  { name: 'eFluor 660', category: 'eFluor', excite: 638, emission: 660,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R2_cluster', source: 'cytek_cfluor_guidelines_2021' },

  // ── APC tandems ──────────────────────────────────────────────
  { name: 'APC-R700', category: 'APC-tandem', excite: 638, emission: 700,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R4_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'APC-Cy5.5', category: 'APC-tandem', excite: 638, emission: 690,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    is_tandem: true, source: 'cytek_cfluor_guidelines_2021' },
  { name: 'APC-Cy7', category: 'APC-tandem', excite: 638, emission: 774,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R7_cluster', is_tandem: true,
    source: 'biolegend_miniguide_2025', aliases: ['APC/Cyanine7'] },
  { name: 'APC-H7', category: 'APC-tandem', excite: 638, emission: 774,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R7_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'APC-eFluor 780', category: 'APC-tandem', excite: 638, emission: 780,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R7_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'APC-Vio 770', category: 'APC-tandem', excite: 638, emission: 770,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'R7_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'APC-Alexa Fluor 700', category: 'APC-tandem', excite: 638, emission: 723,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'R4_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'APC-Alexa Fluor 750', category: 'APC-tandem', excite: 638, emission: 776,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'R7_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'APC-C750', category: 'APC-tandem', excite: 638, emission: 776,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'R7_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'APC/Fire 750', category: 'APC-Fire', excite: 638, emission: 774,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R7_cluster', is_tandem: true,
    source: 'biolegend_miniguide_2025' },
  { name: 'APC/Fire 810', category: 'APC-Fire', excite: 638, emission: 807,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R8_cluster', is_tandem: true,
    source: 'biolegend_miniguide_2025' },

  // ── BioLegend Spark NIR / Red ────────────────────────────────
  { name: 'Spark NIR 685', category: 'BioLegend Spark', excite: 638, emission: 685,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    source: 'biolegend_miniguide_2025' },
  { name: 'Spark Red 718', category: 'BioLegend Spark', excite: 638, emission: 711,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },

  // ── Cytek cFluor Red ─────────────────────────────────────────
  { name: 'cFluor R659', category: 'cFluor', excite: 638, emission: 659,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'R1_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor R668', category: 'cFluor', excite: 638, emission: 668,
    brightness_index: 5, brightness_source: 'cytek_si_2021',
    similarity_group: 'R2_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor R685', category: 'cFluor', excite: 638, emission: 685,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor R720', category: 'cFluor', excite: 638, emission: 720,
    brightness_index: 5, brightness_source: 'cytek_si_2021',
    similarity_group: 'R4_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor R780', category: 'cFluor', excite: 638, emission: 780,
    brightness_index: 1, brightness_source: 'cytek_si_2021',
    similarity_group: 'R7_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'cFluor R840', category: 'cFluor', excite: 638, emission: 810,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'R8_cluster', is_tandem: true,
    source: 'cytek_cfluor_guidelines_2021' },

  // ── Bio-Rad StarBright Red (SBR) ─────────────────────────────
  { name: 'SBR670', category: 'Bio-Rad StarBright', excite: 638, emission: 670,
    brightness_index: 5, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Red 670'] },
  { name: 'SBR715', category: 'Bio-Rad StarBright', excite: 638, emission: 715,
    brightness_index: 5, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Red 715'] },
  { name: 'SBR775', category: 'Bio-Rad StarBright', excite: 638, emission: 775,
    brightness_index: 3, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Red 775'] },
  { name: 'SBR815', category: 'Bio-Rad StarBright', excite: 638, emission: 815,
    brightness_index: 2, brightness_source: 'biorad_ze5_visual',
    source: 'biorad_starbright_brochure', aliases: ['StarBright Red 815'] },

  // ── BD Horizon Real Red ──────────────────────────────────────
  { name: 'RR688', category: 'BD Horizon Real', excite: 638, emission: 688,
    brightness_index: 5, brightness_source: 'bd_real_normalized',
    conventional_ok: false, source: 'bd_horizon_real_table_2025',
    aliases: ['BD Horizon RealRed 688'],
    substitutes: ['Alexa Fluor 660', 'Spark NIR 685', 'NovaFluor Red 685', 'cFluor R685'] },
  { name: 'R718', category: 'BD R718', excite: 638, emission: 718,
    brightness_index: 4, brightness_source: 'thermo_si_chart_2025',
    similarity_group: 'R4_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['BD Horizon Red 718'] },

  // ── Thermo NovaFluor Red (spectral only) ─────────────────────
  { name: 'NovaFluor Red 660', category: 'NovaFluor', excite: 638, excite_max_nm: 637, emission: 659,
    brightness_index: 2, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF R660'] },
  { name: 'NovaFluor Red 685', category: 'NovaFluor', excite: 638, excite_max_nm: 637, emission: 685,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog',
    aliases: ['NF R685', 'NovaFluor R685'] },
  { name: 'NovaFluor Red 700', category: 'NovaFluor', excite: 638, excite_max_nm: 639, emission: 700,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF R700'] },
  { name: 'NovaFluor Red 710', category: 'NovaFluor', excite: 638, excite_max_nm: 639, emission: 710,
    brightness_index: 3, brightness_source: 'thermo_si_chart_2025',
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF R710'] },
  { name: 'NovaFluor Red 725', category: 'NovaFluor', excite: 638, excite_max_nm: 636, emission: 725,
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF R725'] },
  { name: 'NovaFluor Red 755', category: 'NovaFluor', excite: 638, excite_max_nm: 636, emission: 755,
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF R755'] },
  { name: 'NovaFluor Red 800', category: 'NovaFluor', excite: 638, excite_max_nm: 637, emission: 799,
    conventional_ok: false, source: 'thermo_novafluor_catalog', aliases: ['NF R800'] },

  // ── R2 cluster reference dyes ────────────────────────────────
  { name: 'CellTrace Far Red', category: 'Thermo CellTrace', excite: 638, emission: 661,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'R1_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Vio 667', category: 'Miltenyi Vio', excite: 638, emission: 667,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'R2_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'VioBright 667', category: 'Miltenyi VioBright', excite: 638, emission: 667,
    brightness_index: 4, brightness_source: 'cytek_si_2021',
    similarity_group: 'R2_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Janelia Fluor 646', category: 'Janelia Fluor', excite: 638, emission: 664,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'R2_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'NorthernLights 637', category: 'NorthernLights', excite: 638, emission: 657,
    brightness_index: 2, brightness_source: 'cytek_si_2021',
    similarity_group: 'R2_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['NL637'] },
  { name: 'redFluor 710', category: 'Tonbo redFluor', excite: 638, emission: 710,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'R4_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Ghost Dye Red 710', category: 'Tonbo Ghost Dye', excite: 638, emission: 710,
    brightness_index: 3, brightness_source: 'cytek_si_2021',
    similarity_group: 'R4_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'Ghost Dye Red 780', category: 'Tonbo Ghost Dye', excite: 638, emission: 780,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'R7_cluster', source: 'cytek_cfluor_guidelines_2021' },

  // ── Red viability ────────────────────────────────────────────
  { name: 'LIVE/DEAD Far Red', category: 'LIVE/DEAD', excite: 638, emission: 665,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'R2_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'LIVE/DEAD Near-IR', category: 'LIVE/DEAD', excite: 638, emission: 750,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'R7_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['LIVE/DEAD NIR'] },
  { name: 'Fixable Viability Stain 660', category: 'BD FVS', excite: 638, emission: 660,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'R2_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['FVS 660'] },
  { name: 'Fixable Viability Stain 700', category: 'BD FVS', excite: 638, emission: 700,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'R4_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['FVS 700'] },
  { name: 'Fixable Viability Stain 780', category: 'BD FVS', excite: 638, emission: 780,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'R7_cluster', source: 'cytek_cfluor_guidelines_2021',
    aliases: ['FVS 780'] },
  { name: 'Zombie R685', category: 'BioLegend Zombie', excite: 638, emission: 685,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Zombie R718', category: 'BioLegend Zombie', excite: 638, emission: 711,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Zombie NIR', category: 'BioLegend Zombie', excite: 638, emission: 746,
    brightness_index: 3, brightness_source: 'biolegend_published',
    source: 'biolegend_miniguide_2025' },
  { name: 'Helix NP NIR', category: 'BioLegend Helix NP', excite: 638, emission: 660,
    brightness_index: 3, brightness_source: 'biolegend_published',
    similarity_group: 'R2_cluster', source: 'biolegend_miniguide_2025' },
  { name: 'TO-PRO-3', category: 'DNA dye', excite: 638, emission: 661,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'R2_cluster', source: 'thermo_published' },
  { name: 'SYTOX Deep Red', category: 'SYTOX', excite: 638, emission: 670,
    brightness_index: 2, brightness_source: 'manufacturer_published',
    similarity_group: 'R2_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'DRAQ5', category: 'DNA dye', excite: 638, emission: 697,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'DRAQ7', category: 'DNA dye', excite: 638, emission: 695,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    source: 'cytek_cfluor_guidelines_2021' },
  { name: 'ViaKrome 638', category: 'Beckman ViaKrome', excite: 638, emission: 660,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    similarity_group: 'R1_cluster', source: 'cytek_cfluor_guidelines_2021' },
  { name: 'ViaKrome 808', category: 'Beckman ViaKrome', excite: 808, emission: 850,
    brightness_index: 3, brightness_source: 'manufacturer_published',
    source: 'cytek_cfluor_guidelines_2021' },
];

// =============================================================================
// _normalize() — fills in defaults so downstream code can rely on every field
// being present. Compact entries above just specify non-default values.
// =============================================================================
function _normalize(d) {
  return {
    name:                  d.name,
    aliases:               d.aliases || [],
    category:              d.category,
    excite:                d.excite,
    excite_alt:            d.excite_alt || [],
    excite_max_nm:         (d.excite_max_nm !== undefined) ? d.excite_max_nm : null,
    emission:              d.emission,
    brightness_index:      (d.brightness_index !== undefined) ? d.brightness_index : null,
    brightness_source:     d.brightness_source || 'no_data',
    similarity_group:      d.similarity_group || null,
    is_tandem:             d.is_tandem === true,
    conventional_ok:       (d.conventional_ok !== undefined) ? d.conventional_ok : true,
    unique_spectral_space: d.unique_spectral_space === true,
    substitutes:           d.substitutes || [],
    status:                d.status || 'active',
    replaced_by:           d.replaced_by || null,
    source:                d.source || 'unknown'
  };
}

const DYES = _RAW_DYES.map(_normalize);

// =============================================================================
// Lookup helpers — exported for use by scoring.js and the UI
// =============================================================================

/**
 * Find a dye by name or any alias. Case-insensitive.
 * Returns the normalized dye object or null.
 */
function getDye(name) {
  if (!name) return null;
  const target = String(name).trim().toLowerCase();
  return DYES.find(d =>
    d.name.toLowerCase() === target ||
    (d.aliases && d.aliases.some(a => a.toLowerCase() === target))
  ) || null;
}

/**
 * Returns true if both dyes share the same similarity_group.
 * Used by scoring.js to short-circuit SI to 1.0 for spectrally-identical dyes.
 */
function dyesShareSimilarityGroup(nameA, nameB) {
  const a = getDye(nameA);
  const b = getDye(nameB);
  if (!a || !b) return false;
  if (!a.similarity_group || !b.similarity_group) return false;
  return a.similarity_group === b.similarity_group;
}

/**
 * Returns true if a dye is usable in conventional mode.
 * Unknown dyes default to true (don't block on missing metadata).
 */
function isConventionalOk(name) {
  const d = getDye(name);
  return d ? d.conventional_ok : true;
}

// =============================================================================
// Export to window (browser scripts) and CommonJS (Node, tests)
// =============================================================================
if (typeof window !== 'undefined') {
  window.DYES                       = DYES;
  window.getDye                     = getDye;
  window.dyesShareSimilarityGroup   = dyesShareSimilarityGroup;
  window.isConventionalOk           = isConventionalOk;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DYES, getDye, dyesShareSimilarityGroup, isConventionalOk };
}
